"""
collection of urls to meetup groups by city/geo location
"""

# austin, tx
austin_groups = ['https://www.meetup.com/Data-Science-ODSC-Austin/',
				 'https://www.meetup.com/North-Austin-Pythonistas/',
				 'https://www.meetup.com/PyLadies-ATX/',
				 'https://www.meetup.com/austinwebpythonusergroup/',
				 'https://www.meetup.com/AustinLearnPython/',
				 'https://www.meetup.com/PyData-Austin/',
				 'https://www.meetup.com/North-Austin-Pythonistas/',
				 'https://www.meetup.com/Aspiring-Data-Scientist-Community/',
				 'https://www.meetup.com/austinpython/']
# houston, tx
houston_groups = ['https://www.meetup.com/python-14/',
				  'https://www.meetup.com/Houston-Data-Science/',
				  'https://www.meetup.com/ODSC-Houston-Data-Science/',
				  'https://www.meetup.com/Houston_PyLadies/',
				  'https://www.meetup.com/PyData-Houston/',
				  'https://www.meetup.com/Byte-Academy-Houston-Python-FinTech-Blockchain/',
				  'https://www.meetup.com/North-Houston-Data-Analytics-and-Machine-Learning/',
				  'https://www.meetup.com/GA-Houston-Coding-Data-Design-Digital-Marketing/',
				  'https://www.meetup.com/Flatiron-School-Houston-Coding-Community/',
				  'https://www.meetup.com/Houston-Scrum-Users-Group/']
# san francisco (bay area), ca
sfo_groups = ['https://www.meetup.com/San-Francisco-Python-Drinkup/',
			  'https://www.meetup.com/sfpython/',
			  'https://www.meetup.com/East-Bay-Python/',
			  'https://www.meetup.com/Python-for-Bioinformatics/',
			  'https://www.meetup.com/San-Francisco-Python-Hack-Night/',
			  'https://www.meetup.com/All-Things-Python/',
			  'https://www.meetup.com/SV-Python-Workshops/',
			  'https://www.meetup.com/Pyninsula-Python-Peninsula-Meetup/',
			  'https://www.meetup.com/Stanford-Python-Meetup/',
			  'https://www.meetup.com/silicon-valley-python/',
			  'https://www.meetup.com/Python-discussion-for-beginners/',
			  'https://www.meetup.com/The-San-Francisco-Flask-Meetup-Group/',
			  'https://www.meetup.com/The-San-Francisco-Django-Meetup-Group/',
			  'https://www.meetup.com/BAyPIGgies/',
			  'https://www.meetup.com/San-Francisco-ODSC/',
			  'https://www.meetup.com/PyLadiesSF/',
			  'https://www.meetup.com/San-Francisco-PyData/',
			  'https://www.meetup.com/software/',
			  'https://www.meetup.com/SFTwisted/',
			  'https://www.meetup.com/Silicon-Valley-ODSC/',
			  'https://www.meetup.com/Oakland-PyLadies/',
			  'https://www.meetup.com/trivalleycoders/',
			  'https://www.meetup.com/Hack-and-Learn/',
			  'https://www.meetup.com/python-beginners/',
			  'https://www.meetup.com/Santa-Cruz-Python/',
			  'https://www.meetup.com/Women-Who-Code-SF/',
			  'https://www.meetup.com/SF-Bay-ACM/']
# boston, ma
boston_groups = ['https://www.meetup.com/New-Hampshire-Python-Group/',
				 'https://www.meetup.com/bostonpython/',
				 'https://www.meetup.com/Learn-Python-Programming/',
				 'https://www.meetup.com/Boston-Twisted-Python/',
				 'https://www.meetup.com/NH-Data-Science-Meetup-Manchester/',
				 'https://www.meetup.com/odsc-open-source-data-science/',
				 'https://www.meetup.com/djangoboston/',
				 'https://www.meetup.com/boston-ai-machine-learning/',
				 'https://www.meetup.com/sports-data-at-sports-innovation-lab/',
				 'https://www.meetup.com/PyLadies-Boston/',
				 'https://www.meetup.com/bostonsoftware/',
				 'https://www.meetup.com/Women-Who-Code-Boston/',
				 'https://www.meetup.com/bostonml/',
				 'https://www.meetup.com/Boston-AI-Network-Artificial-Intelligence-Group/']
# los angeles, ca
lax_groups = ['https://www.meetup.com/OCPython/',
			  'https://www.meetup.com/Python-Data-Science-Los-Angeles/',
			  'https://www.meetup.com/socalpython/',
			  'https://www.meetup.com/lalamp/',
			  'https://www.meetup.com/Python-Hackathons/',
			  'https://www.meetup.com/Santa-Monica-Python-Meetup/',
			  'https://www.meetup.com/SCV-Data-Science-and-Machine-Learning/',
			  'https://www.meetup.com/iepyladies/',
			  'https://www.meetup.com/CodeSCV-Santa-Clarita-Valley/',
			  'https://www.meetup.com/Data-Science-ODSC-Los-Angeles/',
			  'https://www.meetup.com/Pyladies-LA/']
# san dieago, ca
san_diego_groups = ['https://www.meetup.com/pythonsd/',
					 'https://www.meetup.com/San-Diego-Data-Science-Meetup/',
					 'https://www.meetup.com/machine-learning-society-sd/',
					 'https://www.meetup.com/Data-Science-for-Non-Profits/',
					 'https://www.meetup.com/General-Assembly-San-Diego/',
					 'https://www.meetup.com/San-Diego-Jupyter-Meetup/',
					 'https://www.meetup.com/Docker-San-Diego/',
					 'https://www.meetup.com/San-Diego-Women-in-Data-Science/',
					 'https://www.meetup.com/SanDiegoAI/',
					 'https://www.meetup.com/San-Diego-Data-Science-R-Users-Group/',
					 'https://www.meetup.com/Thinkful-San-Diego/',
					 'https://www.meetup.com/Data-Engineering-San-Diego/']
# atlanta, ga
atl_groups = ['https://www.meetup.com/python-atlanta/',
			  'https://www.meetup.com/AtlantaNPUG/',
			  'https://www.meetup.com/Atlanta-Tech-Talks/',
			  'https://www.meetup.com/lit_atlanta/',
			  'https://www.meetup.com/Ansible-Atlanta/',
			  'https://www.meetup.com/openstack-atlanta/',
			  'https://www.meetup.com/HacksHackersATL/',
			  'https://www.meetup.com/Southern-Data-science/',
			  'https://www.meetup.com/Atlanta-Apache-Spark-User-Group/',
			  'https://www.meetup.com/meetup-group-wSeZdhrV/',
			  'https://www.meetup.com/Applied-Data-Science-of-Atlanta/',
			  'https://www.meetup.com/ODSC-Atlanta-Data-Science/']
# san antonio, tx (expanded to 'data science' a bit due to few python groups)
san_antonio_groups = ['https://www.meetup.com/Alamo-City-Python-Group/',
					  'https://www.meetup.com/Alamo-Code-Learners/',
					  'https://www.meetup.com/San-Antonio-Women-in-Machine-Learning-and-Data-Science/',
					  'https://www.meetup.com/San-Antonio-Data-Science/',
					  'https://www.meetup.com/bianalytics/',
					  'https://www.meetup.com/San-Antonio-Artificial-Intelligence-Events/']
# miami, fl
miami_groups = ['https://www.meetup.com/SoFloPy/',
				'https://www.meetup.com/Python-Developers-Miami-Meetup/',
				'https://www.meetup.com/python-miami/',
				'https://www.meetup.com/Miami-PyLadies/',
				'https://www.meetup.com/ODSC-Miami-Data-Science/',
				'https://www.meetup.com/Data-Science-Study-Group-South-Florida/',
				'https://www.meetup.com/South-Florida-DevOps-Group/',
				'https://www.meetup.com/Fort-Lauderdale-Machine-Learning-Meetup/',
				'https://www.meetup.com/breathe-code/',
				'https://www.meetup.com/Miami-Data-Science-Meetup/']
# dallas, tx
dallas_groups = ['https://www.meetup.com/dfwpython/',
				 'https://www.meetup.com/amRobotics/',
				 'https://www.meetup.com/Collin-County-Data-Science-Education/',
				 'https://www.meetup.com/RubyFTW-Fort-Worth-Ruby-User-Group/',
				 'https://www.meetup.com/python4e/',
				 'https://www.meetup.com/Dallas-Women-in-Data/',
				 'https://www.meetup.com/codingdojo-dallas/']
# denver, co
denver_groups = ['https://www.meetup.com/BoulderPython/',
				 'https://www.meetup.com/Denver-Python-Meetup/',
				 'https://www.meetup.com/frpythoneers/',
				 'https://www.meetup.com/PyDENCO/',
				 'https://www.meetup.com/PyData-Denver/',
				 'https://www.meetup.com/Colorado-Data-Science/',
				 'https://www.meetup.com/DevOps-Exchange-DTC-Meetup/',
				 'https://www.meetup.com/Boulder-Women-in-Machine-Learning-and-Data-Science/']
